name: Community Extension Build
on:
  pull_request:

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
    - name: Get all changed description files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          extensions/*/description.yml

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Parse description files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        pip install pyyaml
        python scripts/build.py
        cat env.sh >> $GITHUB_ENV

    - name: Build extension binaries
      uses: ./.github/workflows/_extension_distribution.yml@main
      with:
        duckdb_version: main
        extension_name: ${{ env.COMMUNITY_EXTENSION_NAME }}
        exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'
        repository: ${{ env.COMMUNITY_EXTENSION_GITHUB }}
        ref: ${{ env.COMMUNITY_EXTENSION_REF }}
