name: Community Extension Build
on:
  pull_request:

jobs:
  duckdb-stable-build:
    runs-on: ubuntu-latest
    steps:
    - name: Get all changed description files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          extensions/*/description.yml

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Parse description files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        pip install pyyaml
        python scripts/build.py
        echo "COMMUNITY_EXTENSION_GITHUB=$COMMUNITY_EXTENSION_GITHUB" >> $GITHUB_ENV
        echo "COMMUNITY_EXTENSION_REF=$COMMUNITY_EXTENSION_REF" >> $GITHUB_ENV

    - name: printf
      env:
        COMMUNITY_EXTENSION_GITHUB:  ${{ env.COMMUNITY_EXTENSION_GITHUB }}
      run: |
        echo $COMMUNITY_EXTENSION_GITHUB

    - uses: actions/checkout@v4
      with:
        repository: ${{ env.COMMUNITY_EXTENSION_GITHUB }}
        ref: ${{ env.COMMUNITY_EXTENSION_REF }}
        path: extension-build
        fetch-depth: 0

    # - name: Build extension binaries
    #   uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    #   with:
    #     duckdb_version: main
    #     extension_name: postgres_scanner
    #     exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'
