name: Community Extension Build
on:
  pull_request:

jobs:
  duckdb-stable-build:
    runs-on: ubuntu-latest
    steps:
    - name: Get all changed description files
      id: changed-description-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          extensions/*/description.yml

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Parse description files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-description-files.outputs.all_changed_files }}
      run: |
        ls -R .
        python scripts/build.py

    # - name: Build extension binaries
    #   uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    #   with:
    #     duckdb_version: main
    #     extension_name: postgres_scanner
    #     exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'
